#!/usr/bin/env sh
# Generated by scripts/sync_framework_manifest.py from framework.json.
# Do not edit this file directly.

CW_FRAMEWORK_VERSION='1.2.0'
CW_DEFAULT_PROFILE='generic'
CW_LEGACY_PROFILE='data-science'
CW_STRICT_PROFILE='data-science'
CW_KNOWN_PROFILES='generic data-science software-app database competition-ml investigation deployed-service'
CW_PRESET_PROFILES='data-science software-app database competition-ml investigation deployed-service'
CW_CUSTOM_PROFILE_FILE='chartworkai.profile.json'

cw_profile_known() {
  case "$1" in
    generic|data-science|software-app|database|competition-ml|investigation|deployed-service) return 0 ;;
    *) return 1 ;;
  esac
}

cw_profile_requires_data_contracts() {
  case "$1" in
    data-science|database|competition-ml) return 0 ;;
    *) return 1 ;;
  esac
}

cw_required_files() {
  cat <<'CW_EOF'
PROJECT_CHARTER.md
AGENTS.md
docs/phase_plan.md
STATUS.md
TASKS.md
docs/decisions/README.md
docs/domain/README.md
CW_EOF
}

cw_required_directories() {
  cat <<'CW_EOF'
docs/decisions
docs/handoffs
docs/domain
CW_EOF
}

cw_scaffold_directories() {
  cat <<'CW_EOF'
docs/decisions
docs/handoffs
docs/domain
docs/reproducibility
src
tests
scripts
CW_EOF
}

cw_managed_files() {
  cat <<'CW_EOF'
PROJECT_CHARTER.md
AGENTS.md
STATUS.md
TASKS.md
docs/phase_plan.md
docs/style_guide.md
docs/decisions/README.md
docs/handoffs/README.md
docs/domain/README.md
docs/data/data_dictionary.md
docs/data/lineage.md
docs/data/watchlist.md
chartworkai.profile.json
CW_EOF
}

cw_reference_directories() {
  cat <<'CW_EOF'
templates
agents
prompts
extensions
CW_EOF
}

cw_scaffold_support_files() {
  cat <<'CW_EOF'
scripts/check_framework_compliance.sh
scripts/generate_phase_plan.sh
scripts/framework_config.sh
CW_EOF
}

cw_core_operating_files() {
  cat <<'CW_EOF'
PROJECT_CHARTER.md
AGENTS.md
STATUS.md
TASKS.md
CW_EOF
}

cw_living_documents() {
  cat <<'CW_EOF'
PROJECT_CHARTER.md
AGENTS.md
docs/phase_plan.md
STATUS.md
TASKS.md
docs/data/data_dictionary.md
docs/data/lineage.md
docs/data/watchlist.md
CW_EOF
}

cw_profile_required_files() {
  case "$1" in
    generic)
      cat <<'CW_EOF'
CW_EOF
      ;;
    data-science)
      cat <<'CW_EOF'
docs/data/data_dictionary.md
docs/data/lineage.md
docs/data/watchlist.md
CW_EOF
      ;;
    software-app)
      cat <<'CW_EOF'
CW_EOF
      ;;
    database)
      cat <<'CW_EOF'
docs/data/data_dictionary.md
docs/data/lineage.md
docs/data/watchlist.md
CW_EOF
      ;;
    competition-ml)
      cat <<'CW_EOF'
docs/data/data_dictionary.md
docs/data/lineage.md
docs/data/watchlist.md
CW_EOF
      ;;
    investigation)
      cat <<'CW_EOF'
CW_EOF
      ;;
    deployed-service)
      cat <<'CW_EOF'
CW_EOF
      ;;
  esac
}

cw_profile_required_directories() {
  case "$1" in
    generic)
      cat <<'CW_EOF'
CW_EOF
      ;;
    data-science)
      cat <<'CW_EOF'
docs/data
CW_EOF
      ;;
    software-app)
      cat <<'CW_EOF'
CW_EOF
      ;;
    database)
      cat <<'CW_EOF'
docs/data
CW_EOF
      ;;
    competition-ml)
      cat <<'CW_EOF'
docs/data
CW_EOF
      ;;
    investigation)
      cat <<'CW_EOF'
CW_EOF
      ;;
    deployed-service)
      cat <<'CW_EOF'
CW_EOF
      ;;
  esac
}

cw_profile_scaffold_directories() {
  case "$1" in
    generic)
      cat <<'CW_EOF'
CW_EOF
      ;;
    data-science)
      cat <<'CW_EOF'
docs/data
data/raw
data/external
data/interim
data/processed
reports/figures
reports/tables
reports/draft
CW_EOF
      ;;
    software-app)
      cat <<'CW_EOF'
CW_EOF
      ;;
    database)
      cat <<'CW_EOF'
docs/data
data/raw
data/external
data/interim
data/processed
reports/figures
reports/tables
reports/draft
CW_EOF
      ;;
    competition-ml)
      cat <<'CW_EOF'
docs/data
data/raw
data/external
data/interim
data/processed
reports/figures
reports/tables
reports/draft
CW_EOF
      ;;
    investigation)
      cat <<'CW_EOF'
CW_EOF
      ;;
    deployed-service)
      cat <<'CW_EOF'
CW_EOF
      ;;
  esac
}

cw_profile_default_roles() {
  case "$1" in
    generic)
      cat <<'CW_EOF'
Orchestrator
Domain Expert
Producer
Reviewer
QA / Reproducibility Engineer
CW_EOF
      ;;
    data-science)
      cat <<'CW_EOF'
Orchestrator
Domain Expert
Data Engineer
Analyst
QA / Reproducibility Engineer
CW_EOF
      ;;
    software-app)
      cat <<'CW_EOF'
Orchestrator
Domain Expert
Software Engineer
Frontend Engineer
Deployment Engineer
QA Engineer
CW_EOF
      ;;
    database)
      cat <<'CW_EOF'
Orchestrator
Domain Expert
Data Engineer
External Data Specialist
QA / Reproducibility Engineer
CW_EOF
      ;;
    competition-ml)
      cat <<'CW_EOF'
Orchestrator
Domain Expert
Data Engineer
Analyst
QA / Reproducibility Engineer
CW_EOF
      ;;
    investigation)
      cat <<'CW_EOF'
Orchestrator
Domain Expert
Producer
Fact-checker
QA
CW_EOF
      ;;
    deployed-service)
      cat <<'CW_EOF'
Orchestrator
Domain Expert
Software Engineer
Frontend Engineer
Deployment Engineer
QA
CW_EOF
      ;;
  esac
}

CW_DECISION_DIRECTORY='docs/decisions'
CW_DECISION_GLOB='*.md'
CW_DECISION_EXCLUDE='README.md'
CW_DECISION_MINIMUM='1'

CW_HANDOFF_DIRECTORY='docs/handoffs'
CW_HANDOFF_GLOB='*.md'
CW_HANDOFF_EXCLUDE=''
CW_HANDOFF_MINIMUM='1'

cw_decision_excluded() {
  case "$1" in
    README.md) return 0 ;;
    *) return 1 ;;
  esac
}
