#!/usr/bin/env python3
"""Generate shell and documentation projections of framework.json."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict, Iterable, List

ROOT = Path(__file__).resolve().parents[1]
MANIFEST_PATH = ROOT / "framework.json"
SHELL_PATH = ROOT / "scripts" / "framework_config.sh"

BEGIN = "<!-- BEGIN GENERATED PROFILE TABLE -->"
END = "<!-- END GENERATED PROFILE TABLE -->"


def load_manifest() -> Dict:
    return json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))


def _emit_lines_function(name: str, values: Iterable[str]) -> List[str]:
    return [f"{name}() {{", "  cat <<'CW_EOF'", *values, "CW_EOF", "}", ""]


def _emit_profile_function(name: str, profiles: Dict, key: str) -> List[str]:
    lines = [f"{name}() {{", '  case "$1" in']
    for profile, settings in profiles.items():
        values = settings[key]
        lines.extend([f"    {profile})", "      cat <<'CW_EOF'", *values, "CW_EOF", "      ;;"])
    lines.extend(["  esac", "}", ""])
    return lines


def render_shell(manifest: Dict) -> str:
    profiles = manifest["profiles"]
    known = "|".join(profiles)
    data = "|".join(
        name for name, settings in profiles.items() if settings["requires_data_contracts"]
    )
    strict_profile = next(
        (name for name, settings in profiles.items() if settings["requires_data_contracts"]),
        manifest["default_profile"],
    )
    rules = manifest["presence_rules"]
    lines = [
        "#!/usr/bin/env sh",
        "# Generated by scripts/sync_framework_manifest.py from framework.json.",
        "# Do not edit this file directly.",
        "",
        f"CW_FRAMEWORK_VERSION='{manifest['version']}'",
        f"CW_DEFAULT_PROFILE='{manifest['default_profile']}'",
        f"CW_STRICT_PROFILE='{strict_profile}'",
        f"CW_KNOWN_PROFILES='{' '.join(profiles)}'",
        "",
        "cw_profile_known() {",
        '  case "$1" in',
        f"    {known}) return 0 ;;",
        "    *) return 1 ;;",
        "  esac",
        "}",
        "",
        "cw_profile_requires_data_contracts() {",
        '  case "$1" in',
        f"    {data}) return 0 ;;",
        "    *) return 1 ;;",
        "  esac",
        "}",
        "",
    ]
    lines += _emit_lines_function("cw_required_files", manifest["required_files"])
    lines += _emit_lines_function("cw_required_directories", manifest["required_directories"])
    lines += _emit_lines_function("cw_scaffold_directories", manifest["scaffold_directories"])
    lines += _emit_lines_function("cw_managed_files", manifest["managed_files"])
    lines += _emit_lines_function("cw_reference_directories", manifest["reference_directories"])
    lines += _emit_lines_function("cw_scaffold_support_files", manifest["scaffold_support_files"])
    lines += _emit_lines_function("cw_core_operating_files", manifest["core_operating_files"])
    lines += _emit_lines_function("cw_living_documents", manifest["living_documents"])
    lines += _emit_profile_function(
        "cw_profile_required_files", profiles, "required_files"
    )
    lines += _emit_profile_function(
        "cw_profile_required_directories", profiles, "required_directories"
    )
    lines += _emit_profile_function(
        "cw_profile_scaffold_directories", profiles, "scaffold_directories"
    )
    for prefix, rule in (("DECISION", rules["seed_decision"]), ("HANDOFF", rules["handoff"])):
        lines.extend(
            [
                f"CW_{prefix}_DIRECTORY='{rule['directory']}'",
                f"CW_{prefix}_GLOB='{rule['glob']}'",
                f"CW_{prefix}_EXCLUDE='{' '.join(rule.get('exclude', []))}'",
                f"CW_{prefix}_MINIMUM='{rule['minimum']}'",
                "",
            ]
        )
    decision_excludes = "|".join(rules["seed_decision"].get("exclude", []))
    lines.extend(["cw_decision_excluded() {", '  case "$1" in'])
    if decision_excludes:
        lines.append(f"    {decision_excludes}) return 0 ;;")
    lines.extend(["    *) return 1 ;;", "  esac", "}", ""])
    return "\n".join(lines).rstrip() + "\n"


def render_profile_table(manifest: Dict, prefix: str) -> str:
    lines = [
        BEGIN,
        "| Profile | Deliverable | Data contracts | \"Reproducible\" means |",
        "|---|---|---|---|",
    ]
    for name, profile in manifest["profiles"].items():
        contracts = "required" if profile["requires_data_contracts"] else "not required"
        lines.append(
            f"| [`{name}`]({prefix}{name}.md) | {profile['deliverable']} | "
            f"{contracts} | {profile['verification_summary']} |"
        )
    lines.append(END)
    return "\n".join(lines)


def replace_generated_table(text: str, table: str) -> str:
    start = text.find(BEGIN)
    end = text.find(END)
    if start < 0 or end < start:
        raise ValueError("profile document is missing generated-table markers")
    return text[:start] + table + text[end + len(END) :]


def expected_files(manifest: Dict) -> Dict[Path, str]:
    outputs = {SHELL_PATH: render_shell(manifest)}
    for relative, prefix in (
        ("profiles/README.md", ""),
        ("IMPLEMENTATION_GUIDE.md", "profiles/"),
    ):
        path = ROOT / relative
        text = path.read_text(encoding="utf-8")
        outputs[path] = replace_generated_table(text, render_profile_table(manifest, prefix))
    return outputs


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Fail if generated files drift.")
    args = parser.parse_args()
    outputs = expected_files(load_manifest())
    stale = [path for path, expected in outputs.items() if not path.exists() or path.read_text(encoding="utf-8") != expected]
    if args.check:
        if stale:
            for path in stale:
                print(f"out of date: {path.relative_to(ROOT)}")
            return 1
        print("framework manifest projections are current")
        return 0
    for path, expected in outputs.items():
        path.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
